// src/app/(admin)/layout.tsx

import type { Metadata } from "next";
import "../globals.css";
import SideBar from "@/components/sidebar";
import Navbar from "@/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    
    <div className="flex h-screen bg-gray-50">
    <SideBar />
  
    <div className="flex-1 flex flex-col">
      <Navbar />
  
      <main className="flex-1 p-6 overflow-auto">
        {children}
      </main>
    </div>
  </div>
  
  );
}